version: "3.9"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - sqlite_data:/app/data/db
    environment:
      - PYTHONUNBUFFERED=1
    depends_on: []

volumes:
  sqlite_data:
